# Generated by Django 4.1.5 on 2023-01-30 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="system_user_histories",
            options={"verbose_name": "System_User_Historie"},
        ),
    ]
