# Generated by Django 4.1.5 on 2023-02-13 04:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_alter_system_user_histories_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="system",
            name="name",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="systems",
                to="user.configuresystems",
            ),
        ),
        migrations.AlterField(
            model_name="system_user_histories",
            name="system",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="System_Histories",
                to="user.system",
            ),
        ),
        migrations.AlterField(
            model_name="system_user_histories",
            name="system_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="System_User_Histories",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
